blank_issues_enabled: false

contact_links:
  - name: 📚 MMClassification Documentation
    url: https://mmclassification.readthedocs.io/en/latest/
    about: Check if your question is answered in docs
  - name: 💬 Forum
    url: https://github.com/open-mmlab/mmclassification/discussions
    about: Ask general usage questions and discuss with other MMClassification community members
  - name: 🌐 Explore OpenMMLab
    url: https://openmmlab.com/
    about: Get know more about OpenMMLab
